config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  resources :releases, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    resources :reviews, only: [:create, :new, :destroy, :edit, :update]
  end

  resources :reviews, only: [:create, :new, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :destroy]
  resources :genres, only: [:show]
  #resources :comments, only: [:show, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :releases do
        resources :reviews
        end
      end
    end

  namespace :api do
    namespace :v1 do
      resources :reviews
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :releases
      end
    end
  end

  resources :users

  root "releases#index"
end

app/models/release.rb
class Release < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true
  validates :year, presence: true, inclusion: { in: 1850..Date.today.year, message: 'is not valid' }
  validates :no_of_tracks, presence: true, numericality: true
  validates :album_art_url, format: { with: /\A(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/, message: "is invalid" }

  belongs_to :user
  has_many :reviews
  has_many :release_genres
  has_many :genres, through: :release_genres
end

app/controllers/api/v1/releases_controller.rb
class Api::V1::ReleasesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render json: Release.all
  end

  def show
    render json: Release.find(params[:id])
  end

end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController

  def index
    if params[:search]
      @releases = Release.where('artist ILIKE ?', "%#{params[:search]}%").order('created_at DESC')
      if @releases.empty? && !Release.all.empty?
        @releases = "Your search has found nothing"
      end
      render 'application/search'
    else
      @releases_slider = Release.order(updated_at: :desc).limit(3)
      @releases = Release.all
    end
  end

  def show
    @release = Release.find(params[:id])
    @release_genres = @release.genres
  end

  def new
    @genre_collection = Genre.all
    @release = Release.new
  end

  def create
    if current_user
      @user = current_user
      @release = Release.new(release_params)
      @release.user = @user
      @release.genres = Genre.where(id: params[:release][:genre_ids])
      if @release.save
        flash[:notice] = "Release saved successfully."
        redirect_to release_path(@release)
      else
        @genre_collection = Genre.all
        render :new
      end
    else
      flash[:notice] = "You must be logged in"
      redirect_to new_user_session_path
    end
  end

  def edit
    @release = Release.find(params[:id])
    @genre_collection = Genre.all
  end

  def update
    @release = Release.find(params[:id])
    if @release.update(release_params)
      flash[:notice] = "Release successfully updated"
      redirect_to release_path(@release)
    else
      @genre_collection = Genre.all
      render :edit
    end
  end

  def destroy
      release = Release.find(params[:id])
      destroy_release(release)
      flash[:notice] = "Release successfully deleted"
      redirect_to root_path
  end

  private

  def release_params
    params.require(:release).permit(
      :title,
      :artist,
      :performer,
      :year,
      :studio,
      :no_of_tracks,
      :album_art_url,
      :description,
      :search
    )
  end
end

app/views/releases/edit.html.erb
<div class="row">
  <div class="release-header">
    <h1 class="small-12 large-8 small-centered"> Edit This Release </h1>
  </div>
</div>
    <div class="row">
      <div class="small-12 large-8 small-centered">
        <%= form_for(@release) do |f| %>
          <% if @release.errors.any? %>
            <div id="error_explanation" class="callout warning">
              <h4><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h4>

              <ul class="no-bullet">
              <% @release.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="release-form">
            <div class="field">
              <%= f.label :title %><br />
              <%= f.text_field :title, :input_html => { :value => @release.title } %>
            </div>

            <div class="field">
              <%= f.label :artist %><br />
              <%= f.text_field :artist, :input_html => { :value => @release.artist } %>
            </div>

            <div class="field">
              <%= f.label :performer %> <br />
              <%= f.text_field :performer, :input_html => { :value => @release.performer } %>
            </div>

            <div class="field">
              <%= f.label :year %> <br />
              <%= f.text_field :year, :input_html => { :value => @release.year } %>
            </div>

            <div class="field">
              <%= f.label :studio %> <br />
              <%= f.text_field :studio, :input_html => { :value => @release.studio } %>
            </div>

            <div class="field">
              <%= f.label :no_of_tracks %> <br />
              <%= f.text_field :no_of_tracks, :input_html => { :value => @release.no_of_tracks } %>
            </div>

            <div class="field">
              <%= f.label :album_art_url %> <br />
              <%= f.text_field :album_art_url, :input_html => { :value => @release.album_art_url } %>
            </div>

            <div class="field">
              <%= f.collection_check_boxes :genre_ids, @genre_collection, :id, :name %>
            </div>

            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description, :input_html => { :value => @release.description } %>
            </div>

            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>

          <%= link_to 'Delete', @release, method: :delete, data: { confirm: 'Are you sure you want to delete this release?' } %> |
          <%= link_to 'Back', releases_path(@release) %>
        </div>
      </div>
    </div>

app/views/releases/index.html.erb
<div class="row">
  <h1 class="welcome"> Welcome to the Kensai Music DB </h1>

  <%= react_component("ReleaseIndexContainer") %>

</div>

app/views/releases/new.html.erb
<div class="row">
  <div class="release-header">
    <h1 class="small-12 large-8 small-centered"> New Release Form </h1>
  </div>
</div>
    <div class="row">
      <div class="small-12 large-8 small-centered">
      <%= form_for(@release) do |f| %>

      <% if @release.errors.any? %>
        <div id="error_explanation" class="callout warning">
          <h5><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h5>

          <ul class="no-bullet">
          <% @release.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="release-form">
        <div class="field">
          <%= f.label :title %> <br />
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :artist %> <br />
          <%= f.text_field :artist %>
        </div>
        <div class="field">
          <%= f.label :performer %> <br />
          <%= f.text_field :performer %>
        </div>
        <div class="field">
          <%= f.label :year %> <br />
          <%= f.text_field :year %>
        </div>
        <div class="field">
          <%= f.label :studio %> <br />
          <%= f.text_field :studio %>
        </div>
        <div class="field">
          <%= f.label :no_of_tracks %> <br />
          <%= f.text_field :no_of_tracks %>
        </div>
        <div class="field">
          <%= f.label :album_art_url %> <br />
          <%= f.text_field :album_art_url %>
        </div>

        <div class="field check-boxes">
          <% @genre_collection.map do |genre| %>
          <div class="check-box-and-label">
            <input type="checkbox" value="<%= genre.id %>" name="release[genre_ids][]" id="release_genre_ids_<%= genre.id %>">
            <label for="release_genre_ids_<%= genre.id %>"><%= genre.name %></label>
          </div>
          <% end %>
        </div>
        <br>
        <br>

        <div class="field">
          <%= f.label :description %> <br />
          <%= f.text_area :description, placeholder: "Optional"  %>
        </div>

        <div class="actions">
          <%= f.submit value="Add Release"%>
        </div>

        <% end %>
      </div>
    </div>
  </div>

app/views/releases/show.html.erb
<div class="row small-centered">
  <h1> <%=@release.title %> by <%= @release.artist %> </h1>
</div>

<div class="release_container">
  <div class="release_picture">
    <img src="<%=@release.album_art_url%>" height="400" width="400"/>
    <% if current_user == @release.user || current_user.try(:is_admin?)%>
    <div class="row">
      <%= link_to "Edit", edit_release_path(@release) %>
    </div>
    <% end %>
  </div>
  <div class="release_info_div">
    <% unless @release.performer.empty? %>
      <h4 class="release_info_header">Performed By: <%= @release.performer %></h4>
    <% end %>

    <h4 class="release_info_header">Year: <%= @release.year %></h4>

    <% unless @release.studio.empty? %>
      <h4 class="release_info_header">Studio: <%= @release.studio %></h4>
    <% end %>

    <h4 class="release_info_header">No. of Tracks: <%= @release.no_of_tracks %></h4>

    <% unless @release_genres.empty? %>
      <h4 class="release_info_header">Genre(s): </h4>
      <% @release_genres.each do |genre| %>
        | <%= link_to genre.name, genre_path(genre) %> |
      <% end %>
    <% end %>

    <% unless @release.description.empty? %>
    <h4 class="release_info_header"> Description: </h4>
    <p><%= @release.description %></p>
    <% end %>

  </div>
</div>

<br>
<br>
<br>

 <div class="add_review">
  <p>
    <%= link_to 'Add a Review', new_release_review_path(@release) %>
  </p>
  <%= react_component("ReviewContainer", props: { id: request.fullpath[-1] }) %>
</div>