config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  resources :releases, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    resources :reviews, only: [:create, :new, :destroy, :edit, :update]
  end

  resources :reviews, only: [:create, :new, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :destroy]
  resources :genres, only: [:show]
  #resources :comments, only: [:show, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :releases do
        resources :reviews
        end
      end
    end

  namespace :api do
    namespace :v1 do
      resources :reviews
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :releases
      end
    end
  end

  resources :users

  root "releases#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Kensai Music DB" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'hello-world-bundle' %>

    <script src="https://use.fontawesome.com/d07d236a64.js"></script>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Michroma|Open+Sans');
    </style>
    <%= csrf_meta_tags %>
  </head>

  <body class="body-background">
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="topbar_ul_left" data-dropdown-menu>
          <li class="menu-text"><%= link_to "Kensai Music DB", root_path %></li>
          <li>
            <div class="genre">
              <a href="#">Releases by genre </a>
              <ul class="genre-dropdown">
                <% genres = Genre.all %>
                <% genres.each do |genre|  %>
                  <li class="genre-dropdown-content"><%= link_to genre.name, (genre) %></li>
                <% end %>
              </ul>
            </div>
          </li>
          <li><%= link_to "Add a Release", new_release_path%></li>
        </ul>
      </div>

      <div class="top-bar-right">
        <ul class="menu_right">
            <% if user_signed_in? %>
              <li><%= link_to "My Profile", user_path(current_user) %> </li>
              <% if current_user.is_admin? %>
                <li><%= link_to "Admin", users_path %></li>
              <% end %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
            <li>
              <%= form_tag(releases_path, method: :get) do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Artists" %>
                <%= submit_tag 'Search', name: nil %>
              <% end %>
            </li>
        </ul>
      </div>
    </div>
<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>
    </div>
  </div>
<% end %>

    <%= yield %>


    </div>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>